sudo: required

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker run --detach --publish 3306:3306 --env MYSQL_DATABASE=bs_test --env MYSQL_USER=guidesmiths --env MYSQL_PASSWORD=secret --name mysql wangxian/alpine-mysql
  - sleep 10

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
